service: serverless-reason-test

frameworkVersion: "=1.8.0"

# Set this via the Plugin?
package:
  individually: true

plugins:
  - serverless-reason-plugin

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: Test
    compileReason: native
    events:
      - http:
          path: hello
          method: get
  function2:
    handler: Function2
    compileReason: native
    events:
      - http:
          path: function2
          method: get
