service: serverless-reason-test

frameworkVersion: "=1.6.1"

# custom:
#   nativeEntry:
#     - Test
#  jsEntry:
#     - src/currentTime

# Set this via the Plugin?
package:
  individually: true

plugins:
  - serverless-reason-plugin

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: Test
    compileReason: native
    events:
      - http:
          path: hello
          method: get
