service: serverless-reason-test

frameworkVersion: "=1.8.0"

# TODO Warn if not set and fail!
package:
  individually: true

plugins:
  - serverless-reason-plugin

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: Function2
    compileReason: native
    events:
      - http:
          path: hello
          method: get
